### ISSUE TITLE
XModle returns null using Openload

### ISSUE THREAD

**Issue by Mohammad-Ha** [KhunHtetzNaing/xGetter#15]
Thank you for your work on the library. The latest version broke Openload completely in my application.

XGetter 1.8.4 works just fine with Openload, but 1.9.0 caused the XModel to return null/empty, even though the same link works in 1.8.4

Link: https://openload.co/f/-B0eeV9BQ4A/aman.E18.EgyDead.CoM.mkv

System log: 

```
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
2019-06-11 20:16:52.479 927-966/? I/GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@2f2e54c)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
2019-06-11 20:16:52.479 9723-9723/myapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-06-11 20:16:52.480 9723-9723/myapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-06-11 20:16:52.480 9723-9723/myapp W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by Mohammad-Ha** [comment]
The issue is solved using the latest 1.9.1.
