### ISSUE TITLE
  java.lang.NullPointerException: Attempt to invoke interface method 

### ISSUE THREAD

**Issue by jjarroyo** [KhunHtetzNaing/xGetter#49]
![image](https://user-images.githubusercontent.com/5465462/91380926-c82dd880-e7eb-11ea-89c8-e56882181afc.png)

link
https://ok.ru/videoembed/2573978438225

2020-08-26 22:26:06.288 1204-1204/com.dowanimes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dowanimes, PID: 1204
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.htetznaing.lowcostvideo.LowCostVideo$OnTaskCompleted.onTaskCompleted(java.util.ArrayList, boolean)' on a null object reference
        at com.htetznaing.lowcostvideo.Sites.OKRU$1.onResponse(OKRU.java:67)
        at com.androidnetworking.common.ANRequest.deliverSuccessResponse(ANRequest.java:731)
        at com.androidnetworking.common.ANRequest.access$6500(ANRequest.java:80)
        at com.androidnetworking.common.ANRequest$6.run(ANRequest.java:709)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)

**Comment by KhunHtetzNaing** [comment]
Call onFinish() before find()

**Comment by jjarroyo** [comment]
thanks works correctly with ok.ru

I wish it also supports

https://my.mail.ru/video
https://netu.io/
https://mega.nz/

**Comment by hitzhak** [comment]
> thanks works correctly with ok.ru
> 
> I wish it also supports
> 
> https://my.mail.ru/video
> https://netu.io/
> https://mega.nz/

Best is if it can work with 9xbuddy / keepv.id ... Works for more then 100 sites
