### ISSUE TITLE
Openload example link make the app crash

### ISSUE THREAD

**Issue by axel7083** [KhunHtetzNaing/xGetter#5]
I just downlaod the project and compile the apk, I didn't changed the links, and the app crash. I tried to change the link but nothing.

Process: com.htetznaing.xgetterexample, PID: 19946
    java.lang.NullPointerException: replacement == null
        at java.lang.String.replace(String.java:2239)
        at com.htetznaing.xgetter.XGetter$10.onResponse(XGetter.java:526)
        at com.htetznaing.xgetter.XGetter$10.onResponse(XGetter.java:480)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
        at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Unknown Source:2)
        at android.os.Handler.dispatchMessage(Unknown Source:4)
        at android.os.Looper.loop(Unknown Source:139)
        at android.app.ActivityThread.main(Unknown Source:146)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Unknown Source:11)
        at com.android.internal.os.ZygoteInit.main(Unknown Source:198)

**Comment by Smarpit-Singh** [comment]
I think it crashed because the URL you want to open has no movie to return. Try out this URL - https://oload.fun/f/NpBJRGIUNHM

**Comment by axel0070** [comment]
I just open the project with Android studio I didn't change anything except this :

    public void openload(View view) {
        letGo("https://oload.fun/f/NpBJRGIUNHM");
    }

I just copy past the link you gave to me. And the error is still here.

If I click on the log, It notice me that the error was on this line :                     
js = js.replace("HtetzLongString", longString);
with the error : 
Process: com.htetznaing.xgetterexample, PID: 19072
    java.lang.NullPointerException: replacement == null
        at java.lang.String.replace(String.java:2239)

Others links are working fine, but the Openload function is crashing.

**Comment by Smarpit-Singh** [comment]
Does this URL is accessible via browser in your region? 
I just tried out this URL and its Working fine here


![image](https://user-images.githubusercontent.com/27909804/56364075-59aa3500-620b-11e9-908e-cf5dbfa118ab.png)

**Comment by axel0070** [comment]
Okey... I'm very very confused... Actually, I'm not sure but I think I was using an old repository, because I didn't have the same UI. I deleted it, download it again from Github, and now it's working.. my apologies for everything.

**Comment by KhunHtetzNaing** [comment]
I update this lib to 1.9 
Plz try latest version @axel0070

**Comment by axel0070** [comment]
> I update this lib to 1.9
> Plz try latest version @axel0070

It work fine !

**Comment by hitzhak** [comment]
Hi ,
The crash appers when the video is not exist , the way to verify i have is to use the openload api ask for captch token ... If it return without the capth ,the video is not exist any mm more
Thanks
